(()=>{'use strict';
const EXTRA={
pl:{
'Settings':'Ustawienia','Guide & Help':'Przewodnik i pomoc','Price Finder':'Wyszukiwarka cen','Calculator':'Kalkulator',
'Suggested Improvements':'Sugerowane usprawnienia','Reset all suggestions':'Resetuj wszystkie sugestie','Reduce material usage':'Zmniejsz zużycie materiału',
'Lowering infill, wall count or supports can reduce material usage. Test the effect here first.':'Zmniejszenie wypełnienia, liczby ścian lub podpór może ograniczyć zużycie materiału. Najpierw sprawdź efekt tutaj.',
'High impact':'Duży wpływ','Medium impact':'Średni wpływ','Lower impact':'Mniejszy wpływ','Current':'Obecnie','Suggested':'Sugerowane','New profit':'Nowy zysk','Live Result':'Wynik na żywo',
'Reduce labour time':'Skróć czas pracy','Test removing setup, cleanup or other hands-on time from each print.':'Sprawdź, co się stanie po skróceniu czasu przygotowania, sprzątania lub innych czynności przy każdym wydruku.',
'Lower delivery cost':'Obniż koszt dostawy','Compare the lower reference rate below with what you currently pay.':'Porównaj niższą stawkę referencyjną z tym, co obecnie płacisz.',
'Adjust selling price':'Dostosuj cenę sprzedaży','A small price change can make a big difference once fees are included.':'Niewielka zmiana ceny może mieć duży wpływ po uwzględnieniu opłat.',
'Use cheaper material':'Użyj tańszego materiału','Test a lower material cost per print while keeping the same print settings.':'Sprawdź niższy koszt materiału na wydruk przy zachowaniu tych samych ustawień.',
'Current profit':'Bieżący zysk','Break-even Price':'Cena progu rentowności','Target price · 30% margin':'Cena docelowa · marża 30%','Sales price':'Cena sprzedaży',
'Per batch':'Na partię','Per print':'Na wydruk','Minimum price to not lose money':'Minimalna cena bez straty','Using current fee assumptions':'Przy obecnych założeniach opłat','Change below to test it':'Zmień poniżej, aby sprawdzić',
'Material usage':'Zużycie materiału','Labour saved':'Oszczędzony czas pracy','Delivery':'Dostawa','Selling price':'Cena sprzedaży','Material cost':'Koszt materiału',
'Apply these changes to calculator':'Zastosuj te zmiany w kalkulatorze','Copy summary':'Kopiuj podsumowanie','Still not profitable?':'Nadal bez zysku?',
'See the full 3D Printing Profit Guide ↗':'Zobacz pełny przewodnik po zyskownym druku 3D ↗','Tip:':'Wskazówka:','These suggestions are estimates based on your current settings. Adjust any value and the result updates in real time.':'Te sugestie są szacunkami na podstawie bieżących ustawień. Zmień dowolną wartość, a wynik zaktualizuje się w czasie rzeczywistym.',
'Currently at a loss':'Obecnie strata','Currently profitable':'Obecnie zysk','Add your print costs':'Dodaj koszty wydruku','Use the sliders below to test changes in real time before applying them.':'Użyj suwaków poniżej, aby na bieżąco testować zmiany przed ich zastosowaniem.',
'You\'re losing ':'Tracisz ',' per batch item.':' na sztuce w partii.','With these changes the estimate moves into profit.':'Po tych zmianach szacunek przechodzi na zysk.','Keep adjusting the suggestions to see where the loss closes.':'Dostosowuj sugestie, aby zobaczyć, gdzie strata znika.',
'Profit Toolkit':'Narzędzia zysku','See where your money goes, test changes safely and price your print with the current fee assumptions.':'Zobacz, gdzie idą pieniądze, bezpiecznie testuj zmiany i wyceniaj wydruk przy obecnych założeniach opłat.',
'What If? — test changes before you make them':'Co jeśli? — testuj zmiany przed ich wprowadzeniem','Cost Breakdown — see what is eating the margin':'Podział kosztów — zobacz, co zabiera marżę','Price Ladder — see the price needed for different margins':'Drabina cen — zobacz ceny potrzebne dla różnych marż','Bulk Buy — check savings on material and packaging':'Zakup hurtowy — sprawdź oszczędności materiału i opakowań','Sell Where? — test a different selling channel':'Gdzie sprzedawać? — przetestuj inny kanał sprzedaży',
'Production cost per print':'Koszt produkcji na wydruk','Production subtotal':'Suma produkcji','Batch production cost':'Koszt produkcji partii','List sales':'Sprzedaż wg ceny bazowej','Batch discount':'Rabat partii','Sales after discount':'Sprzedaż po rabacie','Platform/payment fees':'Opłaty platformy/płatności','Delivery charged':'Opłata pobrana za dostawę','Batch profit':'Zysk z partii'
},
de:{
'Settings':'Einstellungen','Guide & Help':'Anleitung & Hilfe','Price Finder':'Preissuche','Calculator':'Kalkulator',
'Suggested Improvements':'Verbesserungsvorschläge','Reset all suggestions':'Alle Vorschläge zurücksetzen','Reduce material usage':'Materialverbrauch reduzieren',
'Lowering infill, wall count or supports can reduce material usage. Test the effect here first.':'Weniger Infill, Wände oder Stützen können den Materialverbrauch senken. Teste den Effekt zuerst hier.',
'High impact':'Hoher Einfluss','Medium impact':'Mittlerer Einfluss','Lower impact':'Geringerer Einfluss','Current':'Aktuell','Suggested':'Vorschlag','New profit':'Neuer Gewinn','Live Result':'Live-Ergebnis',
'Reduce labour time':'Arbeitszeit reduzieren','Test removing setup, cleanup or other hands-on time from each print.':'Teste weniger Einrichtungs-, Reinigungs- oder sonstige Handarbeit pro Druck.',
'Lower delivery cost':'Versandkosten senken','Compare the lower reference rate below with what you currently pay.':'Vergleiche den günstigeren Referenztarif mit deinen aktuellen Kosten.',
'Adjust selling price':'Verkaufspreis anpassen','A small price change can make a big difference once fees are included.':'Eine kleine Preisänderung kann nach Gebühren einen großen Unterschied machen.',
'Use cheaper material':'Günstigeres Material verwenden','Test a lower material cost per print while keeping the same print settings.':'Teste niedrigere Materialkosten pro Druck bei gleichen Druckeinstellungen.',
'Current profit':'Aktueller Gewinn','Break-even Price':'Break-even-Preis','Target price · 30% margin':'Zielpreis · 30 % Marge','Sales price':'Verkaufspreis',
'Per batch':'Pro Charge','Per print':'Pro Druck','Minimum price to not lose money':'Mindestpreis ohne Verlust','Using current fee assumptions':'Mit aktuellen Gebührenannahmen','Change below to test it':'Unten ändern, um zu testen',
'Material usage':'Materialverbrauch','Labour saved':'Gesparte Arbeitszeit','Delivery':'Versand','Selling price':'Verkaufspreis','Material cost':'Materialkosten',
'Apply these changes to calculator':'Diese Änderungen auf den Rechner anwenden','Copy summary':'Zusammenfassung kopieren','Still not profitable?':'Noch nicht profitabel?',
'See the full 3D Printing Profit Guide ↗':'Vollständige Anleitung für profitablen 3D-Druck ↗','Tip:':'Tipp:','These suggestions are estimates based on your current settings. Adjust any value and the result updates in real time.':'Diese Vorschläge sind Schätzungen auf Basis deiner aktuellen Einstellungen. Jede Änderung aktualisiert das Ergebnis in Echtzeit.',
'Currently at a loss':'Derzeit Verlust','Currently profitable':'Derzeit profitabel','Add your print costs':'Druckkosten hinzufügen','Use the sliders below to test changes in real time before applying them.':'Teste mit den Reglern Änderungen in Echtzeit, bevor du sie anwendest.',
'You\'re losing ':'Du verlierst ',' per batch item.':' pro Chargenstück.','With these changes the estimate moves into profit.':'Mit diesen Änderungen wird die Schätzung profitabel.','Keep adjusting the suggestions to see where the loss closes.':'Passe die Vorschläge weiter an, bis der Verlust verschwindet.',
'Profit Toolkit':'Gewinn-Werkzeugkasten','See where your money goes, test changes safely and price your print with the current fee assumptions.':'Sieh, wohin dein Geld geht, teste Änderungen sicher und kalkuliere mit den aktuellen Gebührenannahmen.',
'What If? — test changes before you make them':'Was wäre wenn? — Änderungen vorab testen','Cost Breakdown — see what is eating the margin':'Kostenaufteilung — was schmälert die Marge?','Price Ladder — see the price needed for different margins':'Preisstufen — notwendiger Preis für verschiedene Margen','Bulk Buy — check savings on material and packaging':'Großeinkauf — Material- und Verpackungsersparnis prüfen','Sell Where? — test a different selling channel':'Wo verkaufen? — anderen Verkaufskanal testen',
'Production cost per print':'Produktionskosten pro Druck','Production subtotal':'Produktionssumme','Batch production cost':'Produktionskosten der Charge','List sales':'Listenumsatz','Batch discount':'Chargenrabatt','Sales after discount':'Umsatz nach Rabatt','Platform/payment fees':'Plattform-/Zahlungsgebühren','Delivery charged':'Berechneter Versand','Batch profit':'Chargengewinn'
},
fr:{
'Settings':'Paramètres','Guide & Help':'Guide et aide','Price Finder':'Recherche de prix','Calculator':'Calculateur',
'Suggested Improvements':'Améliorations suggérées','Reset all suggestions':'Réinitialiser les suggestions','Reduce material usage':'Réduire la consommation de matériau',
'Lowering infill, wall count or supports can reduce material usage. Test the effect here first.':'Réduire le remplissage, les parois ou les supports peut diminuer le matériau utilisé. Testez l’effet ici.',
'High impact':'Fort impact','Medium impact':'Impact moyen','Lower impact':'Impact moindre','Current':'Actuel','Suggested':'Suggéré','New profit':'Nouveau bénéfice','Live Result':'Résultat en direct',
'Reduce labour time':'Réduire le temps de travail','Test removing setup, cleanup or other hands-on time from each print.':'Testez une réduction du temps de préparation, de nettoyage ou d’autres tâches manuelles.',
'Lower delivery cost':'Réduire le coût de livraison','Compare the lower reference rate below with what you currently pay.':'Comparez le tarif de référence inférieur à ce que vous payez actuellement.',
'Adjust selling price':'Ajuster le prix de vente','A small price change can make a big difference once fees are included.':'Une petite variation de prix peut faire une grande différence après les frais.',
'Use cheaper material':'Utiliser un matériau moins cher','Test a lower material cost per print while keeping the same print settings.':'Testez un coût de matériau inférieur par impression avec les mêmes paramètres.',
'Current profit':'Bénéfice actuel','Break-even Price':'Prix d’équilibre','Target price · 30% margin':'Prix cible · marge de 30 %','Sales price':'Prix de vente',
'Per batch':'Par lot','Per print':'Par impression','Minimum price to not lose money':'Prix minimum sans perte','Using current fee assumptions':'Avec les frais actuels','Change below to test it':'Modifiez ci-dessous pour tester',
'Material usage':'Consommation de matériau','Labour saved':'Temps de travail économisé','Delivery':'Livraison','Selling price':'Prix de vente','Material cost':'Coût du matériau',
'Apply these changes to calculator':'Appliquer ces changements au calculateur','Copy summary':'Copier le résumé','Still not profitable?':'Toujours pas rentable ?',
'See the full 3D Printing Profit Guide ↗':'Voir le guide complet sur la rentabilité en impression 3D ↗','Tip:':'Astuce :','These suggestions are estimates based on your current settings. Adjust any value and the result updates in real time.':'Ces suggestions sont des estimations basées sur vos réglages actuels. Modifiez une valeur et le résultat se met à jour en temps réel.',
'Currently at a loss':'Actuellement en perte','Currently profitable':'Actuellement rentable','Add your print costs':'Ajoutez vos coûts d’impression','Use the sliders below to test changes in real time before applying them.':'Utilisez les curseurs pour tester les changements en temps réel avant de les appliquer.',
'You\'re losing ':'Vous perdez ',' per batch item.':' par article du lot.','With these changes the estimate moves into profit.':'Avec ces changements, l’estimation devient rentable.','Keep adjusting the suggestions to see where the loss closes.':'Continuez à ajuster les suggestions jusqu’à supprimer la perte.',
'Profit Toolkit':'Boîte à outils rentabilité','See where your money goes, test changes safely and price your print with the current fee assumptions.':'Voyez où va votre argent, testez des changements en toute sécurité et fixez le prix avec les frais actuels.',
'What If? — test changes before you make them':'Et si ? — testez les changements avant de les appliquer','Cost Breakdown — see what is eating the margin':'Répartition des coûts — ce qui réduit la marge','Price Ladder — see the price needed for different margins':'Échelle de prix — prix nécessaires pour différentes marges','Bulk Buy — check savings on material and packaging':'Achat en volume — vérifiez les économies de matériau et d’emballage','Sell Where? — test a different selling channel':'Où vendre ? — testez un autre canal de vente',
'Production cost per print':'Coût de production par impression','Production subtotal':'Sous-total de production','Batch production cost':'Coût de production du lot','List sales':'Ventes au prix catalogue','Batch discount':'Remise du lot','Sales after discount':'Ventes après remise','Platform/payment fees':'Frais de plateforme/paiement','Delivery charged':'Livraison facturée','Batch profit':'Bénéfice du lot'
},
es:{
'Settings':'Ajustes','Guide & Help':'Guía y ayuda','Price Finder':'Buscador de precios','Calculator':'Calculadora',
'Suggested Improvements':'Mejoras sugeridas','Reset all suggestions':'Restablecer sugerencias','Reduce material usage':'Reducir el uso de material',
'Lowering infill, wall count or supports can reduce material usage. Test the effect here first.':'Reducir el relleno, las paredes o los soportes puede reducir el material usado. Prueba el efecto aquí.',
'High impact':'Alto impacto','Medium impact':'Impacto medio','Lower impact':'Menor impacto','Current':'Actual','Suggested':'Sugerido','New profit':'Nuevo beneficio','Live Result':'Resultado en directo',
'Reduce labour time':'Reducir tiempo de trabajo','Test removing setup, cleanup or other hands-on time from each print.':'Prueba a reducir el tiempo de preparación, limpieza u otras tareas manuales.',
'Lower delivery cost':'Reducir coste de entrega','Compare the lower reference rate below with what you currently pay.':'Compara la tarifa de referencia más baja con lo que pagas actualmente.',
'Adjust selling price':'Ajustar precio de venta','A small price change can make a big difference once fees are included.':'Un pequeño cambio de precio puede marcar una gran diferencia tras incluir las comisiones.',
'Use cheaper material':'Usar material más barato','Test a lower material cost per print while keeping the same print settings.':'Prueba un coste de material menor por impresión manteniendo los mismos ajustes.',
'Current profit':'Beneficio actual','Break-even Price':'Precio de equilibrio','Target price · 30% margin':'Precio objetivo · margen del 30 %','Sales price':'Precio de venta',
'Per batch':'Por lote','Per print':'Por impresión','Minimum price to not lose money':'Precio mínimo sin pérdidas','Using current fee assumptions':'Con las comisiones actuales','Change below to test it':'Cámbialo abajo para probar',
'Material usage':'Uso de material','Labour saved':'Tiempo de trabajo ahorrado','Delivery':'Entrega','Selling price':'Precio de venta','Material cost':'Coste de material',
'Apply these changes to calculator':'Aplicar estos cambios a la calculadora','Copy summary':'Copiar resumen','Still not profitable?':'¿Aún no es rentable?',
'See the full 3D Printing Profit Guide ↗':'Ver la guía completa de rentabilidad de impresión 3D ↗','Tip:':'Consejo:','These suggestions are estimates based on your current settings. Adjust any value and the result updates in real time.':'Estas sugerencias son estimaciones basadas en tus ajustes actuales. Cambia cualquier valor y el resultado se actualiza en tiempo real.',
'Currently at a loss':'Actualmente en pérdidas','Currently profitable':'Actualmente rentable','Add your print costs':'Añade tus costes de impresión','Use the sliders below to test changes in real time before applying them.':'Usa los controles de abajo para probar cambios en tiempo real antes de aplicarlos.',
'You\'re losing ':'Estás perdiendo ',' per batch item.':' por unidad del lote.','With these changes the estimate moves into profit.':'Con estos cambios, la estimación pasa a ser rentable.','Keep adjusting the suggestions to see where the loss closes.':'Sigue ajustando las sugerencias para ver dónde desaparece la pérdida.',
'Profit Toolkit':'Herramientas de beneficio','See where your money goes, test changes safely and price your print with the current fee assumptions.':'Consulta a dónde va tu dinero, prueba cambios con seguridad y calcula el precio con las comisiones actuales.',
'What If? — test changes before you make them':'¿Qué pasaría? — prueba cambios antes de aplicarlos','Cost Breakdown — see what is eating the margin':'Desglose de costes — descubre qué reduce el margen','Price Ladder — see the price necesario para diferentes márgenes':'Escala de precios — ve el precio necesario para distintos márgenes','Bulk Buy — check savings on material and packaging':'Compra al por mayor — comprueba el ahorro en material y embalaje','Sell Where? — test a different selling channel':'¿Dónde vender? — prueba otro canal de venta',
'Production cost per print':'Coste de producción por impresión','Production subtotal':'Subtotal de producción','Batch production cost':'Coste de producción del lote','List sales':'Ventas sin descuento','Batch discount':'Descuento del lote','Sales after discount':'Ventas tras descuento','Platform/payment fees':'Comisiones de plataforma/pago','Delivery charged':'Entrega cobrada','Batch profit':'Beneficio del lote'
},
it:{
'Settings':'Impostazioni','Guide & Help':'Guida e aiuto','Price Finder':'Ricerca prezzi','Calculator':'Calcolatore',
'Suggested Improvements':'Miglioramenti suggeriti','Reset all suggestions':'Reimposta suggerimenti','Reduce material usage':'Riduci uso del materiale',
'High impact':'Alto impatto','Medium impact':'Impatto medio','Lower impact':'Impatto ridotto','Current':'Attuale','Suggested':'Suggerito','New profit':'Nuovo profitto','Live Result':'Risultato in tempo reale',
'Reduce labour time':'Riduci il tempo di lavoro','Lower delivery cost':'Riduci il costo di consegna','Adjust selling price':'Modifica il prezzo di vendita','Use cheaper material':'Usa un materiale più economico',
'Current profit':'Profitto attuale','Break-even Price':'Prezzo di pareggio','Target price · 30% margin':'Prezzo obiettivo · margine 30%','Sales price':'Prezzo di vendita',
'Per batch':'Per lotto','Per print':'Per stampa','Minimum price to not lose money':'Prezzo minimo senza perdita','Using current fee assumptions':'Con le commissioni attuali','Change below to test it':'Modifica sotto per provare',
'Material usage':'Uso del materiale','Labour saved':'Lavoro risparmiato','Delivery':'Consegna','Selling price':'Prezzo di vendita','Material cost':'Costo del materiale',
'Apply these changes to calculator':'Applica queste modifiche al calcolatore','Copy summary':'Copia riepilogo','Still not profitable?':'Non è ancora redditizio?',
'See the full 3D Printing Profit Guide ↗':'Vedi la guida completa alla redditività della stampa 3D ↗','Tip:':'Suggerimento:','Currently at a loss':'Attualmente in perdita','Currently profitable':'Attualmente redditizio','Add your print costs':'Aggiungi i costi di stampa',
'You\'re losing ':'Stai perdendo ',' per batch item.':' per pezzo del lotto.','With these changes the estimate moves into profit.':'Con queste modifiche la stima passa in profitto.','Keep adjusting the suggestions to see where the loss closes.':'Continua a modificare i suggerimenti finché la perdita non scompare.',
'Profit Toolkit':'Strumenti di profitto','What If? — test changes before you make them':'E se? — prova le modifiche prima di applicarle','Cost Breakdown — see what is eating the margin':'Analisi dei costi — cosa riduce il margine','Price Ladder — see the price needed for different margins':'Scala prezzi — prezzo necessario per diversi margini','Bulk Buy — check savings on material and packaging':'Acquisto in volume — controlla il risparmio','Sell Where? — test a different selling channel':'Dove vendere? — prova un altro canale',
'Production cost per print':'Costo di produzione per stampa','Production subtotal':'Subtotale produzione','Batch production cost':'Costo di produzione del lotto','List sales':'Vendite senza sconto','Batch discount':'Sconto lotto','Sales after discount':'Vendite dopo lo sconto','Platform/payment fees':'Commissioni piattaforma/pagamento','Delivery charged':'Consegna addebitata','Batch profit':'Profitto del lotto'
},
nl:{
'Settings':'Instellingen','Guide & Help':'Handleiding & hulp','Price Finder':'Prijszoeker','Calculator':'Calculator',
'Suggested Improvements':'Voorgestelde verbeteringen','Reset all suggestions':'Alle suggesties resetten','Reduce material usage':'Materiaalverbruik verlagen',
'High impact':'Grote impact','Medium impact':'Gemiddelde impact','Lower impact':'Lagere impact','Current':'Huidig','Suggested':'Suggestie','New profit':'Nieuwe winst','Live Result':'Live resultaat',
'Reduce labour time':'Arbeidstijd verlagen','Lower delivery cost':'Bezorgkosten verlagen','Adjust selling price':'Verkoopprijs aanpassen','Use cheaper material':'Goedkoper materiaal gebruiken',
'Current profit':'Huidige winst','Break-even Price':'Break-evenprijs','Target price · 30% margin':'Doelprijs · 30% marge','Sales price':'Verkoopprijs',
'Per batch':'Per batch','Per print':'Per print','Minimum price to not lose money':'Minimumprijs zonder verlies','Using current fee assumptions':'Met huidige kosten','Change below to test it':'Pas hieronder aan om te testen',
'Material usage':'Materiaalverbruik','Labour saved':'Bespaarde arbeidstijd','Delivery':'Levering','Selling price':'Verkoopprijs','Material cost':'Materiaalkosten',
'Apply these changes to calculator':'Deze wijzigingen toepassen op calculator','Copy summary':'Samenvatting kopiëren','Still not profitable?':'Nog steeds niet winstgevend?',
'See the full 3D Printing Profit Guide ↗':'Volledige gids voor winstgevende 3D-printing ↗','Tip:':'Tip:','Currently at a loss':'Momenteel verlies','Currently profitable':'Momenteel winstgevend','Add your print costs':'Voeg printkosten toe',
'You\'re losing ':'Je verliest ',' per batch item.':' per batch-item.','With these changes the estimate moves into profit.':'Met deze wijzigingen wordt de schatting winstgevend.','Keep adjusting the suggestions to see where the loss closes.':'Blijf de suggesties aanpassen tot het verlies verdwijnt.',
'Profit Toolkit':'Winsttools','What If? — test changes before you make them':'Wat als? — test wijzigingen vooraf','Cost Breakdown — see what is eating the margin':'Kostenverdeling — wat drukt de marge?','Price Ladder — benodigde prijs voor marges':'Prijsladder — benodigde prijs voor verschillende marges','Bulk Buy — check savings on material and packaging':'Bulkinkoop — besparing op materiaal en verpakking','Sell Where? — test a different selling channel':'Waar verkopen? — test een ander verkoopkanaal',
'Production cost per print':'Productiekosten per print','Production subtotal':'Productiesubtotaal','Batch production cost':'Productiekosten batch','List sales':'Verkoop zonder korting','Batch discount':'Batchkorting','Sales after discount':'Verkoop na korting','Platform/payment fees':'Platform-/betaalkosten','Delivery charged':'Doorberekende levering','Batch profit':'Batchwinst'
},
pt:{
'Settings':'Definições','Guide & Help':'Guia e ajuda','Price Finder':'Pesquisa de preços','Calculator':'Calculadora',
'Suggested Improvements':'Melhorias sugeridas','Reset all suggestions':'Repor sugestões','Reduce material usage':'Reduzir consumo de material',
'High impact':'Alto impacto','Medium impact':'Impacto médio','Lower impact':'Menor impacto','Current':'Atual','Suggested':'Sugerido','New profit':'Novo lucro','Live Result':'Resultado em tempo real',
'Reduce labour time':'Reduzir tempo de trabalho','Lower delivery cost':'Reduzir custo de entrega','Adjust selling price':'Ajustar preço de venda','Use cheaper material':'Usar material mais barato',
'Current profit':'Lucro atual','Break-even Price':'Preço de equilíbrio','Target price · 30% margin':'Preço alvo · margem de 30%','Sales price':'Preço de venda',
'Per batch':'Por lote','Per print':'Por impressão','Minimum price to not lose money':'Preço mínimo sem perda','Using current fee assumptions':'Com as taxas atuais','Change below to test it':'Altere abaixo para testar',
'Material usage':'Consumo de material','Labour saved':'Tempo de trabalho poupado','Delivery':'Entrega','Selling price':'Preço de venda','Material cost':'Custo do material',
'Apply these changes to calculator':'Aplicar estas alterações à calculadora','Copy summary':'Copiar resumo','Still not profitable?':'Ainda não é rentável?',
'See the full 3D Printing Profit Guide ↗':'Ver o guia completo de rentabilidade da impressão 3D ↗','Tip:':'Sugestão:','Currently at a loss':'Atualmente em prejuízo','Currently profitable':'Atualmente rentável','Add your print costs':'Adicione os custos de impressão',
'You\'re losing ':'Está a perder ',' per batch item.':' por unidade do lote.','With these changes the estimate moves into profit.':'Com estas alterações a estimativa passa a lucro.','Keep adjusting the suggestions to see where the loss closes.':'Continue a ajustar as sugestões até eliminar o prejuízo.',
'Profit Toolkit':'Ferramentas de lucro','What If? — test changes before you make them':'E se? — teste alterações antes de as aplicar','Cost Breakdown — veja o que está a consumir a margem':'Análise de custos — veja o que reduz a margem','Price Ladder — veja o preço necessário para diferentes margens':'Escada de preços — preços para diferentes margens','Bulk Buy — check savings on material and packaging':'Compra em volume — verifique as poupanças','Sell Where? — test a different selling channel':'Onde vender? — teste outro canal',
'Production cost per print':'Custo de produção por impressão','Production subtotal':'Subtotal de produção','Batch production cost':'Custo de produção do lote','List sales':'Vendas sem desconto','Batch discount':'Desconto do lote','Sales after discount':'Vendas após desconto','Platform/payment fees':'Taxas de plataforma/pagamento','Delivery charged':'Entrega cobrada','Batch profit':'Lucro do lote'
},
cs:{
'Settings':'Nastavení','Guide & Help':'Průvodce a nápověda','Price Finder':'Vyhledávač cen','Calculator':'Kalkulačka',
'Suggested Improvements':'Navržená zlepšení','Reset all suggestions':'Resetovat všechny návrhy','Reduce material usage':'Snížit spotřebu materiálu',
'High impact':'Velký dopad','Medium impact':'Střední dopad','Lower impact':'Menší dopad','Current':'Aktuální','Suggested':'Návrh','New profit':'Nový zisk','Live Result':'Výsledek v reálném čase',
'Reduce labour time':'Snížit pracovní čas','Lower delivery cost':'Snížit cenu doručení','Adjust selling price':'Upravit prodejní cenu','Use cheaper material':'Použít levnější materiál',
'Current profit':'Aktuální zisk','Break-even Price':'Cena bodu zvratu','Target price · 30% margin':'Cílová cena · marže 30 %','Sales price':'Prodejní cena',
'Per batch':'Na dávku','Per print':'Na tisk','Minimum price to not lose money':'Minimální cena bez ztráty','Using current fee assumptions':'Při současných poplatcích','Change below to test it':'Upravte níže pro test',
'Material usage':'Spotřeba materiálu','Labour saved':'Ušetřený pracovní čas','Delivery':'Doručení','Selling price':'Prodejní cena','Material cost':'Cena materiálu',
'Apply these changes to calculator':'Použít tyto změny v kalkulačce','Copy summary':'Kopírovat shrnutí','Still not profitable?':'Stále není zisk?',
'See the full 3D Printing Profit Guide ↗':'Zobrazit úplného průvodce ziskovým 3D tiskem ↗','Tip:':'Tip:','Currently at a loss':'Nyní ve ztrátě','Currently profitable':'Nyní ziskové','Add your print costs':'Přidejte náklady tisku',
'You\'re losing ':'Ztrácíte ',' per batch item.':' na kus dávky.','With these changes the estimate moves into profit.':'Po těchto změnách se odhad dostává do zisku.','Keep adjusting the suggestions to see where the loss closes.':'Upravujte návrhy, dokud ztráta nezmizí.',
'Profit Toolkit':'Nástroje zisku','What If? — test changes before you make them':'Co kdyby? — otestujte změny před použitím','Cost Breakdown — see what is eating the margin':'Rozpis nákladů — co snižuje marži?','Price Ladder — see the cenu needed for different margins':'Cenový žebřík — ceny pro různé marže','Bulk Buy — check savings on material and packaging':'Velkoobchod — zkontrolujte úspory','Sell Where? — test a different selling channel':'Kde prodávat? — otestujte jiný kanál',
'Production cost per print':'Výrobní náklad na tisk','Production subtotal':'Mezisoučet výroby','Batch production cost':'Výrobní náklad dávky','List sales':'Prodej bez slevy','Batch discount':'Sleva dávky','Sales after discount':'Prodej po slevě','Platform/payment fees':'Poplatky platformy/platby','Delivery charged':'Účtované doručení','Batch profit':'Zisk dávky'
},
sv:{
'Settings':'Inställningar','Guide & Help':'Guide och hjälp','Price Finder':'Prissökning','Calculator':'Kalkylator',
'Suggested Improvements':'Föreslagna förbättringar','Reset all suggestions':'Återställ alla förslag','Reduce material usage':'Minska materialåtgång',
'High impact':'Hög påverkan','Medium impact':'Medelhög påverkan','Lower impact':'Lägre påverkan','Current':'Aktuell','Suggested':'Föreslagen','New profit':'Ny vinst','Live Result':'Live-resultat',
'Reduce labour time':'Minska arbetstid','Lower delivery cost':'Sänk leveranskostnad','Adjust selling price':'Justera försäljningspris','Use cheaper material':'Använd billigare material',
'Current profit':'Aktuell vinst','Break-even Price':'Nollpunktspris','Target price · 30% margin':'Målpris · 30 % marginal','Sales price':'Försäljningspris',
'Per batch':'Per batch','Per print':'Per utskrift','Minimum price to not lose money':'Minimipris utan förlust','Using current fee assumptions':'Med aktuella avgifter','Change below to test it':'Ändra nedan för att testa',
'Material usage':'Materialåtgång','Labour saved':'Sparad arbetstid','Delivery':'Leverans','Selling price':'Försäljningspris','Material cost':'Materialkostnad',
'Apply these changes to calculator':'Tillämpa ändringarna i kalkylatorn','Copy summary':'Kopiera sammanfattning','Still not profitable?':'Fortfarande inte lönsamt?',
'See the full 3D Printing Profit Guide ↗':'Se hela guiden för lönsam 3D-utskrift ↗','Tip:':'Tips:','Currently at a loss':'Förlust just nu','Currently profitable':'Lönsam just nu','Add your print costs':'Lägg till utskriftskostnader',
'You\'re losing ':'Du förlorar ',' per batch item.':' per batchartikel.','With these changes the estimate moves into profit.':'Med dessa ändringar blir uppskattningen lönsam.','Keep adjusting the suggestions to see where the loss closes.':'Justera förslagen tills förlusten försvinner.',
'Profit Toolkit':'Vinstverktyg','What If? — test changes before you make them':'Tänk om? — testa ändringar innan du använder dem','Cost Breakdown — see what is eating the margin':'Kostnadsfördelning — vad äter upp marginalen?','Price Ladder — see the price needed for different margins':'Prissteg — pris för olika marginaler','Bulk Buy — check savings on material and packaging':'Storköp — kontrollera besparingar','Sell Where? — test a different selling channel':'Var sälja? — testa en annan kanal',
'Production cost per print':'Produktionskostnad per utskrift','Production subtotal':'Produktionssumma','Batch production cost':'Produktionskostnad för batch','List sales':'Försäljning före rabatt','Batch discount':'Batchrabatt','Sales after discount':'Försäljning efter rabatt','Platform/payment fees':'Plattforms-/betalavgifter','Delivery charged':'Debiterad leverans','Batch profit':'Batchvinst'
},
da:{
'Settings':'Indstillinger','Guide & Help':'Guide og hjælp','Price Finder':'Prissøgning','Calculator':'Lommeregner',
'Suggested Improvements':'Foreslåede forbedringer','Reset all suggestions':'Nulstil alle forslag','Reduce material usage':'Reducer materialeforbrug',
'High impact':'Stor effekt','Medium impact':'Mellem effekt','Lower impact':'Lavere effekt','Current':'Aktuel','Suggested':'Forslag','New profit':'Nyt overskud','Live Result':'Resultat i realtid',
'Reduce labour time':'Reducer arbejdstid','Lower delivery cost':'Reducer leveringsomkostning','Adjust selling price':'Juster salgspris','Use cheaper material':'Brug billigere materiale',
'Current profit':'Aktuelt overskud','Break-even Price':'Break-even-pris','Target price · 30% margin':'Målpris · 30 % margen','Sales price':'Salgspris',
'Per batch':'Pr. batch','Per print':'Pr. print','Minimum price to not lose money':'Minimumspris uden tab','Using current fee assumptions':'Med aktuelle gebyrer','Change below to test it':'Rediger nedenfor for at teste',
'Material usage':'Materialeforbrug','Labour saved':'Sparet arbejdstid','Delivery':'Levering','Selling price':'Salgspris','Material cost':'Materialeomkostning',
'Apply these changes to calculator':'Anvend ændringer på lommeregneren','Copy summary':'Kopiér oversigt','Still not profitable?':'Stadig ikke rentabel?',
'See the full 3D Printing Profit Guide ↗':'Se den fulde guide til rentabel 3D-print ↗','Tip:':'Tip:','Currently at a loss':'I underskud nu','Currently profitable':'Rentabel nu','Add your print costs':'Tilføj printomkostninger',
'You\'re losing ':'Du taber ',' per batch item.':' pr. enhed i batchen.','With these changes the estimate moves into profit.':'Med disse ændringer bliver estimatet rentabelt.','Keep adjusting the suggestions to see where the loss closes.':'Juster forslagene, indtil underskuddet forsvinder.',
'Profit Toolkit':'Profitværktøjer','What If? — test changes before you make them':'Hvad hvis? — test ændringer først','Cost Breakdown — see what is eating the margin':'Omkostningsfordeling — hvad spiser marginen?','Price Ladder — se prisen der kræves for forskellige marginer':'Pristrin — pris for forskellige marginer','Bulk Buy — check savings on material and packaging':'Storkøb — se besparelser','Sell Where? — test a different selling channel':'Hvor skal du sælge? — test en anden kanal',
'Production cost per print':'Produktionsomkostning pr. print','Production subtotal':'Produktionssubtotal','Batch production cost':'Produktionsomkostning for batch','List sales':'Salg før rabat','Batch discount':'Batchrabat','Sales after discount':'Salg efter rabat','Platform/payment fees':'Platform-/betalingsgebyrer','Delivery charged':'Opkrævet levering','Batch profit':'Batchfortjeneste'
}
};

const FRAG={pl:{'Find it ':'Znajdź ','cheaper.':'taniej.','Guide & ':'Przewodnik i ','Help.':'pomoc.','PRINTPROFIT • INFORMATION CENTRE':'PRINTPROFIT • CENTRUM INFORMACJI'},de:{'Find it ':'Finde es ','cheaper.':'günstiger.','Guide & ':'Anleitung & ','Help.':'Hilfe.','PRINTPROFIT • INFORMATION CENTRE':'PRINTPROFIT • INFORMATIONSZENTRUM'},fr:{'Find it ':'Trouvez-le ','cheaper.':'moins cher.','Guide & ':'Guide et ','Help.':'aide.','PRINTPROFIT • INFORMATION CENTRE':'PRINTPROFIT • CENTRE D’INFORMATION'},es:{'Find it ':'Encuéntralo ','cheaper.':'más barato.','Guide & ':'Guía y ','Help.':'ayuda.','PRINTPROFIT • INFORMATION CENTRE':'PRINTPROFIT • CENTRO DE INFORMACIÓN'},it:{'Find it ':'Trovalo ','cheaper.':'a un prezzo più basso.','Guide & ':'Guida e ','Help.':'aiuto.','PRINTPROFIT • INFORMATION CENTRE':'PRINTPROFIT • CENTRO INFORMAZIONI'},nl:{'Find it ':'Vind het ','cheaper.':'goedkoper.','Guide & ':'Handleiding & ','Help.':'hulp.','PRINTPROFIT • INFORMATION CENTRE':'PRINTPROFIT • INFORMATIECENTRUM'},pt:{'Find it ':'Encontre-o ','cheaper.':'mais barato.','Guide & ':'Guia e ','Help.':'ajuda.','PRINTPROFIT • INFORMATION CENTRE':'PRINTPROFIT • CENTRO DE INFORMAÇÃO'},cs:{'Find it ':'Najděte to ','cheaper.':'levněji.','Guide & ':'Průvodce a ','Help.':'nápověda.','PRINTPROFIT • INFORMATION CENTRE':'PRINTPROFIT • INFORMAČNÍ CENTRUM'},sv:{'Find it ':'Hitta det ','cheaper.':'billigare.','Guide & ':'Guide och ','Help.':'hjälp.','PRINTPROFIT • INFORMATION CENTRE':'PRINTPROFIT • INFORMATIONSCENTER'},da:{'Find it ':'Find det ','cheaper.':'billigere.','Guide & ':'Guide og ','Help.':'hjælp.','PRINTPROFIT • INFORMATION CENTRE':'PRINTPROFIT • INFORMATIONSCENTER'}};
Object.entries(FRAG).forEach(([lang,map])=>Object.assign(EXTRA[lang]||(EXTRA[lang]={}),map));

const PAGE={
pl:{'Find it cheaper.':'Znajdź taniej.','PRINTPROFIT • PRICE FINDER':'PRINTPROFIT • WYSZUKIWARKA CEN','Compare current tracked UK listings for 3D printers and filament. Sort by total price or unit cost, filter by type, and open the retailer listing to check the live price before you buy.':'Porównuj śledzone oferty 3D-printerów i filamentów w Wielkiej Brytanii. Sortuj po cenie całkowitej lub jednostkowej, filtruj po typie i sprawdzaj aktualną ofertę sprzedawcy.','Search':'Szukaj','Category':'Kategoria','All products':'Wszystkie produkty','Filament':'Filament','3D printers':'Drukarki 3D','Material / type':'Materiał / typ','All types':'Wszystkie typy','Sort by':'Sortuj według','Price: low to high':'Cena: od najniższej','Unit cost: low to high':'Koszt jednostkowy: od najniższego','Name':'Nazwa','Retailer':'Sprzedawca','listings':'ofert','Product':'Produkt','Pack / Build':'Opakowanie / obszar roboczy','Price':'Cena','Unit cost':'Koszt jednostkowy','Updated':'Aktualizacja','Check live ↗':'Sprawdź aktualną cenę ↗','No matching listings':'Brak pasujących ofert','Try a broader search or category.':'Spróbuj szerszego wyszukiwania lub innej kategorii.','How PrintProfit compares prices':'Jak PrintProfit porównuje ceny','Tracked sources':'Śledzone źródła','More stores':'Więcej sklepów','Live-check before buying':'Sprawdź cenę na żywo przed zakupem','Guide & Help':'Przewodnik i pomoc','A simple walkthrough of the current PrintProfit workflow, what the numbers mean, and how to get the most useful result.':'Prosty przewodnik po obecnym działaniu PrintProfit, znaczeniu liczb i sposobie uzyskania najbardziej użytecznego wyniku.','Back to Calculator ›':'Wróć do kalkulatora ›','Settings explained ↓':'Wyjaśnienie ustawień ↓','Using the calculator':'Korzystanie z kalkulatora','Your PrintProfit libraries':'Biblioteki PrintProfit','Understanding the numbers':'Rozumienie liczb','Settings explained':'Wyjaśnienie ustawień','Information & help':'Informacje i pomoc','Why does my result look wrong?':'Dlaczego mój wynik wygląda nieprawidłowo?','What happens when I upload a G-code file?':'Co się dzieje po przesłaniu pliku G-code?','Why did the calculator switch to Batch Pricing?':'Dlaczego kalkulator przełączył się na wycenę zbiorczą?','Why did my fields disappear after opening Guide & Help?':'Dlaczego pola zniknęły po otwarciu przewodnika?','Why did my material change to resin?':'Dlaczego materiał zmienił się na żywicę?','What should I put in the electricity rate?':'Co wpisać w stawce za prąd?','Why can fees and delivery change the result?':'Dlaczego opłaty i dostawa zmieniają wynik?'},
de:{'Find it cheaper.':'Finde es günstiger.','PRINTPROFIT • PRICE FINDER':'PRINTPROFIT • PREISSUCHE','Search':'Suche','Category':'Kategorie','All products':'Alle Produkte','Filament':'Filament','3D printers':'3D-Drucker','Material / type':'Material / Typ','All types':'Alle Typen','Sort by':'Sortieren nach','Price: low to high':'Preis: aufsteigend','Unit cost: low to high':'Stückkosten: aufsteigend','Name':'Name','Retailer':'Händler','listings':'Angebote','Product':'Produkt','Pack / Build':'Packung / Bauraum','Price':'Preis','Unit cost':'Stückkosten','Updated':'Aktualisiert','Check live ↗':'Live-Preis prüfen ↗','No matching listings':'Keine passenden Angebote','Try a broader search or category.':'Versuche eine breitere Suche oder Kategorie.','How PrintProfit compares prices':'So vergleicht PrintProfit Preise','Tracked sources':'Erfasste Quellen','More stores':'Weitere Händler','Live-check before buying':'Vor dem Kauf Live-Preis prüfen','Guide & Help':'Anleitung & Hilfe','A simple walkthrough of the current PrintProfit workflow, what the numbers mean, and how to get the most useful result.':'Ein einfacher Überblick über den aktuellen PrintProfit-Ablauf, die Bedeutung der Zahlen und wie du das beste Ergebnis erhältst.','Back to Calculator ›':'Zurück zum Rechner ›','Settings explained ↓':'Einstellungen erklärt ↓','Using the calculator':'Kalkulator verwenden','Your PrintProfit libraries':'Deine PrintProfit-Bibliotheken','Understanding the numbers':'Zahlen verstehen','Settings explained':'Einstellungen erklärt','Information & help':'Informationen & Hilfe','Why does my result look wrong?':'Warum sieht mein Ergebnis falsch aus?','What happens when I upload a G-code file?':'Was passiert beim Hochladen einer G-Code-Datei?','Why did the calculator switch to Batch Pricing?':'Warum wechselte der Rechner zur Chargenpreisberechnung?','Why did my fields disappear after opening Guide & Help?':'Warum verschwanden meine Felder nach dem Öffnen der Anleitung?','Why did my material change to resin?':'Warum wurde mein Material zu Harz geändert?','What should I put in the electricity rate?':'Was trage ich beim Stromtarif ein?','Why can fees and delivery change the result?':'Warum können Gebühren und Versand das Ergebnis ändern?'},
fr:{'Find it cheaper.':'Trouvez moins cher.','PRINTPROFIT • PRICE FINDER':'PRINTPROFIT • RECHERCHE DE PRIX','Search':'Recherche','Category':'Catégorie','All products':'Tous les produits','Filament':'Filament','3D printers':'Imprimantes 3D','Material / type':'Matériau / type','All types':'Tous les types','Sort by':'Trier par','Price: low to high':'Prix : croissant','Unit cost: low to high':'Coût unitaire : croissant','Name':'Nom','Retailer':'Vendeur','listings':'offres','Product':'Produit','Pack / Build':'Pack / volume','Price':'Prix','Unit cost':'Coût unitaire','Updated':'Mis à jour','Check live ↗':'Vérifier le prix actuel ↗','No matching listings':'Aucune offre correspondante','Try a broader search or category.':'Essayez une recherche ou une catégorie plus large.','How PrintProfit compares prices':'Comment PrintProfit compare les prix','Tracked sources':'Sources suivies','More stores':'Plus de magasins','Live-check before buying':'Vérifier le prix actuel avant l’achat','Guide & Help':'Guide et aide','A simple walkthrough of the current PrintProfit workflow, what the numbers mean, and how to get the most useful result.':'Un guide simple du fonctionnement actuel de PrintProfit, de la signification des chiffres et de la façon d’obtenir le meilleur résultat.','Back to Calculator ›':'Retour au calculateur ›','Settings explained ↓':'Paramètres expliqués ↓','Using the calculator':'Utiliser le calculateur','Your PrintProfit libraries':'Vos bibliothèques PrintProfit','Understanding the numbers':'Comprendre les chiffres','Settings explained':'Paramètres expliqués','Information & help':'Informations et aide','Why does my result look wrong?':'Pourquoi mon résultat semble-t-il incorrect ?','What happens when I upload a G-code file?':'Que se passe-t-il lorsque je téléverse un fichier G-code ?','Why did the calculator switch to Batch Pricing?':'Pourquoi le calculateur est-il passé à la tarification par lot ?','Why did my fields disappear after opening Guide & Help?':'Pourquoi mes champs ont-ils disparu après l’ouverture du guide ?','Why did my material change to resin?':'Pourquoi mon matériau est-il passé en résine ?','What should I put in the electricity rate?':'Que dois-je saisir comme tarif électrique ?','Why can fees and delivery change the result?':'Pourquoi les frais et la livraison peuvent-ils changer le résultat ?'},
es:{'Find it cheaper.':'Encuéntralo más barato.','PRINTPROFIT • PRICE FINDER':'PRINTPROFIT • BUSCADOR DE PRECIOS','Search':'Buscar','Category':'Categoría','All products':'Todos los productos','Filament':'Filamento','3D printers':'Impresoras 3D','Material / type':'Material / tipo','All types':'Todos los tipos','Sort by':'Ordenar por','Price: low to high':'Precio: de menor a mayor','Unit cost: low to high':'Coste unitario: de menor a mayor','Name':'Nombre','Retailer':'Vendedor','listings':'ofertas','Product':'Producto','Pack / Build':'Paquete / volumen','Price':'Precio','Unit cost':'Coste unitario','Updated':'Actualizado','Check live ↗':'Comprobar precio actual ↗','No matching listings':'No hay ofertas coincidentes','Try a broader search or category.':'Prueba una búsqueda o categoría más amplia.','How PrintProfit compares prices':'Cómo compara PrintProfit los precios','Tracked sources':'Fuentes seguidas','More stores':'Más tiendas','Live-check before buying':'Comprueba el precio actual antes de comprar','Guide & Help':'Guía y ayuda','A simple walkthrough of the current PrintProfit workflow, what the numbers mean, and how to get the most useful result.':'Una guía sencilla del flujo actual de PrintProfit, del significado de los números y de cómo obtener el resultado más útil.','Back to Calculator ›':'Volver a la calculadora ›','Settings explained ↓':'Ajustes explicados ↓','Using the calculator':'Uso de la calculadora','Your PrintProfit libraries':'Tus bibliotecas de PrintProfit','Understanding the numbers':'Entender los números','Settings explained':'Ajustes explicados','Information & help':'Información y ayuda','Why does my result look wrong?':'¿Por qué parece incorrecto mi resultado?','What happens when I upload a G-code file?':'¿Qué ocurre al subir un archivo G-code?','Why did the calculator switch to Batch Pricing?':'¿Por qué la calculadora cambió a precios por lote?','Why did my fields disappear after opening Guide & Help?':'¿Por qué desaparecieron mis campos al abrir la guía?','Why did my material change to resin?':'¿Por qué mi material cambió a resina?','What should I put in the electricity rate?':'¿Qué debo poner en la tarifa eléctrica?','Why can fees and delivery change the result?':'¿Por qué las comisiones y la entrega cambian el resultado?'},
it:{'Find it cheaper.':'Trovalo a un prezzo più basso.','PRINTPROFIT • PRICE FINDER':'PRINTPROFIT • RICERCA PREZZI','Search':'Cerca','Category':'Categoria','All products':'Tutti i prodotti','Filament':'Filamento','3D printers':'Stampanti 3D','Material / type':'Materiale / tipo','All types':'Tutti i tipi','Sort by':'Ordina per','Price: low to high':'Prezzo: crescente','Unit cost: low to high':'Costo unitario: crescente','Name':'Nome','Retailer':'Rivenditore','listings':'offerte','Product':'Prodotto','Pack / Build':'Confezione / volume','Price':'Prezzo','Unit cost':'Costo unitario','Updated':'Aggiornato','Check live ↗':'Controlla prezzo attuale ↗','No matching listings':'Nessuna offerta corrispondente','Try a broader search or category.':'Prova una ricerca o categoria più ampia.','How PrintProfit compares prices':'Come PrintProfit confronta i prezzi','Tracked sources':'Fonti monitorate','More stores':'Altri negozi','Live-check before buying':'Controlla il prezzo attuale prima di acquistare','Guide & Help':'Guida e aiuto','A simple walkthrough of the current PrintProfit workflow, what the numbers mean, and how to get the most useful result.':'Una guida semplice al flusso attuale di PrintProfit, al significato dei numeri e a come ottenere il risultato più utile.','Back to Calculator ›':'Torna al calcolatore ›','Settings explained ↓':'Impostazioni spiegate ↓','Using the calculator':'Usare il calcolatore','Your PrintProfit libraries':'Le tue librerie PrintProfit','Understanding the numbers':'Capire i numeri','Settings explained':'Impostazioni spiegate','Information & help':'Informazioni e aiuto','Why does my result look wrong?':'Perché il mio risultato sembra errato?','What happens when I upload a G-code file?':'Cosa succede quando carico un file G-code?','Why did the calculator switch to Batch Pricing?':'Perché il calcolatore è passato al prezzo lotto?','Why did my fields disappear after opening Guide & Help?':'Perché i miei campi sono scomparsi aprendo la guida?','Why did my material change to resin?':'Perché il materiale è passato alla resina?','What should I put in the electricity rate?':'Cosa devo inserire nella tariffa elettrica?','Why can fees and delivery change the result?':'Perché commissioni e consegna possono cambiare il risultato?'},
nl:{'Find it cheaper.':'Vind het goedkoper.','PRINTPROFIT • PRICE FINDER':'PRINTPROFIT • PRIJZOEKER','Search':'Zoeken','Category':'Categorie','All products':'Alle producten','Filament':'Filament','3D printers':'3D-printers','Material / type':'Materiaal / type','All types':'Alle typen','Sort by':'Sorteren op','Price: low to high':'Prijs: laag naar hoog','Unit cost: low to high':'Eenheidskosten: laag naar hoog','Name':'Naam','Retailer':'Verkoper','listings':'aanbiedingen','Product':'Product','Pack / Build':'Verpakking / bouwvolume','Price':'Prijs','Unit cost':'Eenheidskosten','Updated':'Bijgewerkt','Check live ↗':'Actuele prijs bekijken ↗','No matching listings':'Geen overeenkomende aanbiedingen','Try a broader search or category.':'Probeer een bredere zoekopdracht of categorie.','How PrintProfit compares prices':'Hoe PrintProfit prijzen vergelijkt','Tracked sources':'Gevolgde bronnen','More stores':'Meer winkels','Live-check before buying':'Controleer de actuele prijs voor aankoop','Guide & Help':'Handleiding & hulp','A simple walkthrough of the current PrintProfit workflow, what the numbers mean, and how to get the most useful result.':'Een eenvoudige uitleg van de huidige PrintProfit-werkwijze, wat de cijfers betekenen en hoe je het nuttigste resultaat krijgt.','Back to Calculator ›':'Terug naar calculator ›','Settings explained ↓':'Instellingen uitgelegd ↓','Using the calculator':'De calculator gebruiken','Your PrintProfit libraries':'Je PrintProfit-bibliotheken','Understanding the numbers':'De cijfers begrijpen','Settings explained':'Instellingen uitgelegd','Information & help':'Informatie & hulp','Why does my result look wrong?':'Waarom ziet mijn resultaat er verkeerd uit?','What happens when I upload a G-code file?':'Wat gebeurt er wanneer ik een G-codebestand upload?','Why did the calculator switch to Batch Pricing?':'Waarom schakelde de calculator over naar batchprijzen?','Why did my fields disappear after opening Guide & Help?':'Waarom verdwenen mijn velden na het openen van de handleiding?','Why did my material change to resin?':'Waarom veranderde mijn materiaal in hars?','What should I put in the electricity rate?':'Wat vul ik in bij het elektriciteitstarief?','Why can fees and delivery change the result?':'Waarom kunnen kosten en levering het resultaat wijzigen?'},
pt:{'Find it cheaper.':'Encontre mais barato.','PRINTPROFIT • PRICE FINDER':'PRINTPROFIT • PESQUISA DE PREÇOS','Search':'Pesquisar','Category':'Categoria','All products':'Todos os produtos','Filament':'Filamento','3D printers':'Impressoras 3D','Material / type':'Material / tipo','All types':'Todos os tipos','Sort by':'Ordenar por','Price: low to high':'Preço: mais baixo primeiro','Unit cost: low to high':'Custo unitário: mais baixo primeiro','Name':'Nome','Retailer':'Vendedor','listings':'ofertas','Product':'Produto','Pack / Build':'Embalagem / volume','Price':'Preço','Unit cost':'Custo unitário','Updated':'Atualizado','Check live ↗':'Ver preço atual ↗','No matching listings':'Nenhuma oferta correspondente','Try a broader search or category.':'Tente uma pesquisa ou categoria mais ampla.','How PrintProfit compares prices':'Como o PrintProfit compara preços','Tracked sources':'Fontes acompanhadas','More stores':'Mais lojas','Live-check before buying':'Confirme o preço atual antes de comprar','Guide & Help':'Guia e ajuda','A simple walkthrough of the current PrintProfit workflow, what the numbers mean, and how to get the most useful result.':'Um guia simples do fluxo atual do PrintProfit, do significado dos números e de como obter o resultado mais útil.','Back to Calculator ›':'Voltar à calculadora ›','Settings explained ↓':'Definições explicadas ↓','Using the calculator':'Usar a calculadora','Your PrintProfit libraries':'As suas bibliotecas PrintProfit','Understanding the numbers':'Compreender os números','Settings explained':'Definições explicadas','Information & help':'Informação e ajuda','Why does my result look wrong?':'Porque é que o resultado parece errado?','What happens when I upload a G-code file?':'O que acontece quando carrego um ficheiro G-code?','Why did the calculator switch to Batch Pricing?':'Porque é que a calculadora mudou para preço por lote?','Why did my fields disappear after opening Guide & Help?':'Porque desapareceram os meus campos ao abrir o guia?','Why did my material change to resin?':'Porque mudou o meu material para resina?','What should I put in the electricity rate?':'O que devo colocar na tarifa de eletricidade?','Why can fees and delivery change the result?':'Porque podem as taxas e a entrega alterar o resultado?'},
cs:{'Find it cheaper.':'Najděte to levněji.','PRINTPROFIT • PRICE FINDER':'PRINTPROFIT • VYHLEDÁVAČ CEN','Search':'Hledat','Category':'Kategorie','All products':'Všechny produkty','Filament':'Filament','3D printers':'3D tiskárny','Material / type':'Materiál / typ','All types':'Všechny typy','Sort by':'Řadit podle','Price: low to high':'Cena od nejnižší','Unit cost: low to high':'Jednotková cena od nejnižší','Name':'Název','Retailer':'Prodejce','listings':'nabídek','Product':'Produkt','Pack / Build':'Balení / objem','Price':'Cena','Unit cost':'Jednotková cena','Updated':'Aktualizováno','Check live ↗':'Zkontrolovat aktuální cenu ↗','No matching listings':'Žádné odpovídající nabídky','Try a broader search or category.':'Zkuste širší hledání nebo kategorii.','How PrintProfit compares prices':'Jak PrintProfit porovnává ceny','Tracked sources':'Sledované zdroje','More stores':'Další obchody','Live-check before buying':'Před nákupem zkontrolujte aktuální cenu','Guide & Help':'Průvodce a nápověda','A simple walkthrough of the current PrintProfit workflow, what the numbers mean, and how to get the most useful result.':'Jednoduchý průvodce aktuálním postupem PrintProfit, významem čísel a získáním nejpoužitelnějšího výsledku.','Back to Calculator ›':'Zpět na kalkulačku ›','Settings explained ↓':'Vysvětlení nastavení ↓','Using the calculator':'Použití kalkulačky','Your PrintProfit libraries':'Vaše knihovny PrintProfit','Understanding the numbers':'Porozumění číslům','Settings explained':'Vysvětlení nastavení','Information & help':'Informace a nápověda','Why does my result look wrong?':'Proč můj výsledek vypadá špatně?','What happens when I upload a G-code file?':'Co se stane po nahrání souboru G-code?','Why did the calculator switch to Batch Pricing?':'Proč kalkulačka přešla na dávkovou cenu?','Why did my fields disappear after opening Guide & Help?':'Proč po otevření průvodce zmizela moje pole?','Why did my material change to resin?':'Proč se materiál změnil na pryskyřici?','What should I put in the electricity rate?':'Co mám zadat jako sazbu elektřiny?','Why can fees and delivery change the result?':'Proč mohou poplatky a doručení změnit výsledek?'},
sv:{'Find it cheaper.':'Hitta det billigare.','PRINTPROFIT • PRICE FINDER':'PRINTPROFIT • PRISSÖKNING','Search':'Sök','Category':'Kategori','All products':'Alla produkter','Filament':'Filament','3D printers':'3D-skrivare','Material / type':'Material / typ','All types':'Alla typer','Sort by':'Sortera efter','Price: low to high':'Pris: lägst först','Unit cost: low to high':'Enhetskostnad: lägst först','Name':'Namn','Retailer':'Säljare','listings':'erbjudanden','Product':'Produkt','Pack / Build':'Förpackning / byggvolym','Price':'Pris','Unit cost':'Enhetskostnad','Updated':'Uppdaterad','Check live ↗':'Kontrollera aktuellt pris ↗','No matching listings':'Inga matchande erbjudanden','Try a broader search or category.':'Prova en bredare sökning eller kategori.','How PrintProfit compares prices':'Så jämför PrintProfit priser','Tracked sources':'Följda källor','More stores':'Fler butiker','Live-check before buying':'Kontrollera aktuellt pris före köp','Guide & Help':'Guide och hjälp','A simple walkthrough of the current PrintProfit workflow, what the numbers mean, and how to get the most useful result.':'En enkel genomgång av det aktuella PrintProfit-flödet, vad siffrorna betyder och hur du får mest användbara resultat.','Back to Calculator ›':'Tillbaka till kalkylatorn ›','Settings explained ↓':'Inställningar förklarade ↓','Using the calculator':'Använda kalkylatorn','Your PrintProfit libraries':'Dina PrintProfit-bibliotek','Understanding the numbers':'Förstå siffrorna','Settings explained':'Inställningar förklarade','Information & help':'Information och hjälp','Why does my result look wrong?':'Varför ser mitt resultat fel ut?','What happens when I upload a G-code file?':'Vad händer när jag laddar upp en G-code-fil?','Why did the calculator switch to Batch Pricing?':'Varför bytte kalkylatorn till batchpris?','Why did my fields disappear after opening Guide & Help?':'Varför försvann mina fält när jag öppnade guiden?','Why did my material change to resin?':'Varför ändrades mitt material till harts?','What should I put in the electricity rate?':'Vad ska jag ange som eltaxa?','Why can fees and delivery change the result?':'Varför kan avgifter och leverans ändra resultatet?'},
da:{'Find it cheaper.':'Find det billigere.','PRINTPROFIT • PRICE FINDER':'PRINTPROFIT • PRISSØGNING','Search':'Søg','Category':'Kategori','All products':'Alle produkter','Filament':'Filament','3D printers':'3D-printere','Material / type':'Materiale / type','All types':'Alle typer','Sort by':'Sorter efter','Price: low to high':'Pris: lav til høj','Unit cost: low to high':'Enhedspris: lav til høj','Name':'Navn','Retailer':'Forhandler','listings':'tilbud','Product':'Produkt','Pack / Build':'Pakke / byggevolumen','Price':'Pris','Unit cost':'Enhedspris','Updated':'Opdateret','Check live ↗':'Tjek aktuel pris ↗','No matching listings':'Ingen matchende tilbud','Try a broader search or category.':'Prøv en bredere søgning eller kategori.','How PrintProfit compares prices':'Sådan sammenligner PrintProfit priser','Tracked sources':'Fulgte kilder','More stores':'Flere butikker','Live-check before buying':'Tjek den aktuelle pris før køb','Guide & Help':'Guide og hjælp','A simple walkthrough of the current PrintProfit workflow, what the numbers mean, and how to get the most useful result.':'En enkel gennemgang af den aktuelle PrintProfit-arbejdsgang, hvad tallene betyder, og hvordan du får det mest nyttige resultat.','Back to Calculator ›':'Tilbage til lommeregner ›','Settings explained ↓':'Indstillinger forklaret ↓','Using the calculator':'Brug af lommeregneren','Your PrintProfit libraries':'Dine PrintProfit-biblioteker','Understanding the numbers':'Forstå tallene','Settings explained':'Indstillinger forklaret','Information & help':'Information og hjælp','Why does my result look wrong?':'Hvorfor ser mit resultat forkert ud?','What happens when I upload a G-code file?':'Hvad sker der, når jeg uploader en G-code-fil?','Why did the calculator switch to Batch Pricing?':'Hvorfor skiftede lommeregneren til batchpris?','Why did my fields disappear after opening Guide & Help?':'Hvorfor forsvandt mine felter, da jeg åbnede guiden?','Why did my material change to resin?':'Hvorfor blev mit materiale ændret til harpiks?','What should I put in the electricity rate?':'Hvad skal jeg skrive som elpris?','Why can fees and delivery change the result?':'Hvorfor kan gebyrer og levering ændre resultatet?'}
};
Object.entries(PAGE).forEach(([lang,map])=>Object.assign(EXTRA[lang]||(EXTRA[lang]={}),map));

window.__ppExtraI18n=EXTRA;
window.__ppTranslateText=(value,lang)=>{
 const map=EXTRA[lang]||{};
 if(!value)return value;
 if(map[value])return map[value];
 let out=value;
 const keys=Object.keys(map).filter(k=>k.length>=8).sort((a,b)=>b.length-a.length);
 for(const k of keys){if(out.includes(k))out=out.split(k).join(map[k]);}
 return out;
};
window.__ppApplyStandaloneI18n=()=>{
 const lang=(()=>{try{return JSON.parse(localStorage.getItem('printprofit.preferences.v3')||'{}').language||'en';}catch(e){return 'en';}})();
 if(lang==='en')return;
 const trans=window.__ppTranslateText;
 const walk=()=>{
  const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;
  while(n=w.nextNode()){
   if(!n.parentElement||n.parentElement.closest('script,style'))continue;
   const raw=n.nodeValue;if(!raw.trim())continue;
   const next=trans(raw.trim(),lang);
   if(next!==raw.trim())n.nodeValue=n.nodeValue.replace(raw.trim(),next);
  }
  document.documentElement.lang=lang;
 };
 walk();
 if(window.MutationObserver){
  let timer;
  new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(walk,30);}).observe(document.body,{childList:true,subtree:true});
 }
};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>window.__ppApplyStandaloneI18n?.(),{once:true});else window.__ppApplyStandaloneI18n?.();
})();