(()=>{'use strict';
if(window.__printProfitVisualMaster)return;window.__printProfitVisualMaster=true;

const iconSymbols={"calculator":"calculator","cube":"cube","chart":"chart","gear":"settings","folder":"folder","home":"home","search":"search","compare":"compare","book":"book","save":"save","download":"download","upload":"upload","undo":"undo","trash":"trash","printer":"printer","printerSettings":"printer-settings","material":"filament","power":"power","time":"time","labour":"wrench","coins":"coins","delivery":"truck","package":"package","tax":"tax","cash":"cash","tag":"tag","profit":"profit","advisor":"advisor","file":"file"};
const symbolIcon=name=>'<svg viewBox="0 0 48 48" aria-hidden="true" focusable="false"><use href="./assets/printprofit-icon-master.svg#pp-'+(iconSymbols[name]||'cube')+'"></use></svg>';
const icons=Object.fromEntries(Object.keys(iconSymbols).map(name=>[name,symbolIcon(name)]));
Object.assign(icons,{
model:'<svg viewBox="0 0 96 96" aria-hidden="true"><defs><linearGradient id="m1a" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#dffcff"/><stop offset=".42" stop-color="#19d8ff"/><stop offset="1" stop-color="#0066d6"/></linearGradient><linearGradient id="m1b" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#4fe7ff"/><stop offset="1" stop-color="#007de8"/></linearGradient><filter id="m1g"><feGaussianBlur stdDeviation="1.8" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><g filter="url(#m1g)"><rect x="10" y="61" width="76" height="18" rx="5" fill="#102532" stroke="url(#m1a)" stroke-width="2.5"/><rect x="18" y="57" width="60" height="7" rx="3.5" fill="#173746" stroke="#35e3ff" stroke-width="2"/><rect x="25" y="18" width="46" height="39" rx="4" fill="#102532" stroke="#35e3ff" stroke-width="2.5"/><path d="M25 28h46M34 18v-8h28v8" fill="none" stroke="url(#m1a)" stroke-width="3" stroke-linecap="round"/><rect x="40" y="16" width="18" height="13" rx="3" fill="#1a5675" stroke="#e8ffff" stroke-width="2"/><path d="M49 29v13" stroke="#dffcff" stroke-width="3"/><path d="M43 42h12l-6 7z" fill="#19d8ff" stroke="#f4ffff" stroke-width="1.5"/><path d="M33 43h32v12H33z" fill="#0b1f2c" stroke="#19c8ff" stroke-width="2"/><path d="M38 46h22v6H38z" fill="url(#m1b)"/><path d="M37 69h22l-6 7H43z" fill="#0b1e29" stroke="#19d8ff" stroke-width="2"/><path d="M41 70h14" stroke="#dffcff" stroke-width="2.5" stroke-linecap="round"/><path d="M17 65h62" stroke="#ffffff" stroke-opacity=".35" stroke-width="1"/></g></svg>',
printsetup:'<svg viewBox="0 0 96 96" aria-hidden="true"><defs><linearGradient id="m2a" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#f0d8ff"/><stop offset=".5" stop-color="#7C4DFF"/><stop offset="1" stop-color="#5424BA"/></linearGradient><linearGradient id="m2b" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#6f32c9"/><stop offset="1" stop-color="#1c1640"/></linearGradient><filter id="m2g"><feGaussianBlur stdDeviation="2" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><g filter="url(#m2g)"><rect x="10" y="62" width="76" height="17" rx="5" fill="#17112b" stroke="url(#m2a)" stroke-width="2.5"/><rect x="17" y="57" width="62" height="7" rx="3.5" fill="#26184b" stroke="#b77cff" stroke-width="2"/><rect x="24" y="18" width="48" height="39" rx="4" fill="url(#m2b)" stroke="#bf83ff" stroke-width="2.5"/><path d="M24 29h48M33 18V10h30v8" fill="none" stroke="#e8d6ff" stroke-width="3" stroke-linecap="round"/><rect x="39" y="14" width="19" height="14" rx="3" fill="#7c4dff" stroke="#fff" stroke-width="2"/><path d="M48.5 28v13" stroke="#efe2ff" stroke-width="3"/><path d="M43 41h11l-5.5 8z" fill="#d8b5ff" stroke="#fff" stroke-width="1.5"/><rect x="34" y="43" width="28" height="11" rx="2" fill="#291c4b" stroke="#c98dff" stroke-width="2"/><path d="M40 47h16" stroke="#f2dcff" stroke-width="2" stroke-linecap="round"/><circle cx="63" cy="34" r="2.5" fill="#ffccff"/><path d="M38 69h22" stroke="#fff" stroke-width="2.5" stroke-linecap="round"/></g></svg>',
costs:'<svg viewBox="0 0 96 96" aria-hidden="true"><defs><linearGradient id="m3a" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#d7ffe8"/><stop offset=".5" stop-color="#10B981"/><stop offset="1" stop-color="#0D8B62"/></linearGradient><linearGradient id="m3b" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#147A57"/><stop offset="1" stop-color="#12332b"/></linearGradient><filter id="m3g"><feGaussianBlur stdDeviation="2" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><g filter="url(#m3g)"><ellipse cx="75" cy="34" rx="15" ry="7" fill="#17372b" stroke="#10B981" stroke-width="2"/><path d="M60 34v24c0 4 30 4 30 0V34" fill="#10251e" stroke="#10B981" stroke-width="2"/><ellipse cx="75" cy="34" rx="9" ry="3.5" fill="#0a1813" stroke="#73f7aa" stroke-width="1.5"/><path d="M48 24h30v42H18V24z" fill="url(#m3b)" stroke="#bfffe0" stroke-width="2.5" rx="5"/><rect x="23" y="29" width="20" height="10" rx="2" fill="#0b1712" stroke="#10B981" stroke-width="2"/><path d="M27 34h12" stroke="#aaffcf" stroke-width="2.5" stroke-linecap="round"/><g fill="#10211a" stroke="#bfffe0" stroke-width="1.6"><rect x="23" y="44" width="7" height="6" rx="1"/><rect x="33" y="44" width="7" height="6" rx="1"/><rect x="23" y="53" width="7" height="6" rx="1"/><rect x="33" y="53" width="7" height="6" rx="1"/><rect x="23" y="62" width="7" height="6" rx="1"/><rect x="33" y="62" width="7" height="6" rx="1"/></g><circle cx="27" cy="47" r="1" fill="#fff"/><path d="M63 53c5 0 11 2 11 7s-6 7-11 7" fill="none" stroke="#10B981" stroke-width="2.5"/><path d="M61 53h7M61 67h7" stroke="#bfffe0" stroke-width="1.5"/><g><ellipse cx="82" cy="67" rx="11" ry="4" fill="#c6922e" stroke="#ffe7a8" stroke-width="1.5"/><path d="M71 67v7c0 5 22 5 22 0v-7" fill="#d19a2d" stroke="#ffe7a8" stroke-width="1.5"/><ellipse cx="82" cy="67" rx="11" ry="4" fill="none" stroke="#fff0b8" stroke-width="1.2"/><path d="M70 78h24" stroke="#10B981" stroke-width="3" stroke-linecap="round"/></g></g></svg>',
results:'<svg viewBox="0 0 96 96" aria-hidden="true"><defs><linearGradient id="m4a" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#e9fcff"/><stop offset=".4" stop-color="#19d8ff"/><stop offset="1" stop-color="#0066d6"/></linearGradient><filter id="m4g"><feGaussianBlur stdDeviation="2" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><g filter="url(#m4g)"><rect x="16" y="12" width="66" height="62" rx="6" fill="#122531" stroke="url(#m4a)" stroke-width="2.5"/><rect x="21" y="17" width="56" height="48" rx="3" fill="#09151d" stroke="#264654" stroke-width="1.5"/><path d="M29 55V39M43 55V33M57 55V25M71 55V19" stroke="#19c8ff" stroke-width="5" stroke-linecap="round"/><path d="m28 36 13-10 11 5 15-14" fill="none" stroke="#52f2ff" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"/><path d="M65 17h6v6" fill="none" stroke="#77ff7a" stroke-width="3" stroke-linecap="round"/><path d="M9 67h26l-6 10H15z" fill="#0d2733" stroke="#19d8ff" stroke-width="2"/><path d="M14 65h17" stroke="#fff" stroke-width="2"/><rect x="16" y="70" width="22" height="6" rx="2" fill="#19c8ff"/><path d="M13 79h28" stroke="#dffcff" stroke-width="2.5" stroke-linecap="round"/><path d="M74 70h12" stroke="#19d8ff" stroke-width="2.5" stroke-linecap="round"/></g></svg>'
});

const svg=n=>icons[n]||icons.cube;
const goStage=n=>document.querySelector('.pp-step[data-tab="'+n+'"]')?.click();

function build(){
document.getElementById('ppCleanTop')?.remove();
document.getElementById('pp-master-quickcards')?.remove();
document.querySelectorAll('#ppProgressHost,#ppSetupProgress,.pp-progress,.pp-progress-host').forEach(e=>e.style.setProperty('display','none','important'));
document.querySelector('.shell > .header')?.style.setProperty('display','none','important');
document.querySelector('.shell > .hero')?.style.setProperty('display','none','important');
document.getElementById('ppVisualMaster')?.remove();

const top=document.createElement('section');
top.id='ppVisualMaster';
top.setAttribute('aria-label','PrintProfit introduction');

top.innerHTML='<header class="pvm-header"><a class="pvm-brand" href="#home"><img src="./assets/printprofit-logo-orange.svg?v=5" alt="PrintProfit"><span class="pvm-brand-fallback">PrintProfit</span></a>'+
'<nav class="pvm-nav"><button type="button" data-a="home"><span class="pvm-icon">'+svg('home')+'</span>Home</button><button type="button" data-a="projects"><span class="pvm-icon">'+svg('folder')+'</span>My Projects</button><button type="button" data-a="compare"><span class="pvm-icon">'+svg('compare')+'</span>Compare Products</button><button type="button" data-a="guide"><span class="pvm-icon">'+svg('book')+'</span>Guide &amp; Help</button><button type="button" data-a="settings"><span class="pvm-icon">'+svg('gear')+'</span>Settings</button></nav>'+
'<div class="pvm-prefs"><label class="pvm-dark"><span>◐</span><b>Dark Mode</b><input id="pvmDarkMode" type="checkbox"><i></i></label><label class="pvm-language"><span class="pvm-flag"></span><select id="pvmLanguage"><option value="en">EN</option><option value="pl">PL</option><option value="de">DE</option><option value="fr">FR</option><option value="es">ES</option><option value="it">IT</option><option value="nl">NL</option><option value="pt">PT</option><option value="cs">CS</option><option value="sv">SV</option><option value="da">DA</option></select><em>⌄</em></label></div></header>'+
'<div class="pvm-hero"><img class="pvm-bg" src="./assets/hero-hd.webp?v=1" alt="" aria-hidden="true"><div class="pvm-overlay"></div><div class="pvm-copy"><div class="pvm-kicker">3D PRINTING PRICING, MADE SIMPLE</div><h1>Know what it costs.<br><strong>Know what to charge.</strong></h1><p>Accurate 3D printing cost and pricing calculations to help you<br class="pvm-desktop"> price with confidence and maximise your profit.</p><div class="pvm-actions"><button type="button" class="pvm-primary" data-a="calculate"><span>'+svg('calculator')+'</span>Start Calculating <b>›</b></button><button type="button" class="pvm-projects" data-a="projects"><span>'+svg('folder')+'</span>My Projects</button></div></div>'+
'<div class="pvm-tagline pvm-hero-tagline">Print Smarter.<br>Price Better.<br>Profit More.</div></div>'+
'<div class="pvm-journey"><button type="button" data-stage="details"><span class="n one">1</span><span class="jicon">'+svg('model')+'</span><span><strong>Your Model</strong><small>Upload your print &amp; view its data</small></span></button><em>→</em><button type="button" data-stage="machine"><span class="n two">2</span><span class="jicon">'+svg('printsetup')+'</span><span><strong>Print Setup</strong><small>Choose your printer &amp; material</small></span></button><em>→</em><button type="button" data-stage="costs"><span class="n three">3</span><span class="jicon">'+svg('costs')+'</span><span><strong>Costs &amp; Fees</strong><small>Add your business costs</small></span></button><em>→</em><button type="button" data-stage="results"><span class="n four">4</span><span class="jicon">'+svg('results')+'</span><span><strong>Results</strong><small>Review cost, price &amp; profit</small></span></button></div>';

document.body.insertBefore(top,document.body.querySelector('.shell')||document.body.firstChild);const ppSharpenSvg=document.createElement('svg');ppSharpenSvg.setAttribute('aria-hidden','true');ppSharpenSvg.style.cssText='position:absolute;width:0;height:0;overflow:hidden;pointer-events:none';ppSharpenSvg.innerHTML='<defs><filter id="ppSharpen" x="-8%" y="-8%" width="116%" height="116%"><feConvolveMatrix order="3" kernelMatrix="0 -1 0 -1 5 -1 0 -1 0" edgeMode="duplicate"/></filter></defs>';top.appendChild(ppSharpenSvg);

const style=document.createElement('style');
style.id='ppVisualMasterStyles';
style.textContent=
'#ppVisualMaster{width:100%;background:#071018;color:#f5f8fb;font-family:Inter,Segoe UI,system-ui,sans-serif}'+
'#ppVisualMaster *{box-sizing:border-box}#ppVisualMaster button,#ppVisualMaster select{font:inherit}'+
'#ppVisualMaster .pvm-header{height:58px;display:flex;align-items:center;gap:16px;padding:0 clamp(18px,3vw,48px);background:rgba(5,14,20,.98);border-bottom:1px solid #294653;position:relative;z-index:10}'+
'#ppVisualMaster .pvm-brand{width:218px;height:46px;display:flex;align-items:center;flex:0 0 218px;position:relative;text-decoration:none}.pvm-brand img{width:100%;height:46px;object-fit:contain;object-position:left center}.pvm-brand-fallback{display:none;position:absolute;left:0;color:#f5f8fb;font-size:20px;font-weight:900}'+
'#ppVisualMaster .pvm-nav{display:flex;align-items:center;justify-content:center;gap:5px;flex:1;min-width:0}.pvm-nav button{height:48px;padding:0 13px;border:1px solid transparent;border-radius:12px;background:transparent;color:#e1ebef;display:inline-flex;align-items:center;gap:8px;cursor:pointer;font-size:13px;font-weight:850;white-space:nowrap}.pvm-nav button:hover{background:#009FEF0f;color:#fff}.pvm-nav button:first-child{border-color:#009FEF;background:#0c1820}'+
'#ppVisualMaster .pvm-icon{width:27px;height:27px;display:grid;place-items:center;color:#009FEF}.pvm-icon svg{width:24px;height:24px;fill:none;stroke:currentColor;stroke-width:2.25;stroke-linecap:round;stroke-linejoin:round}'+
'#ppVisualMaster .pvm-prefs{display:flex;align-items:center;gap:9px;flex:0 0 auto}.pvm-dark,.pvm-language{height:38px;display:flex;align-items:center;gap:7px;border:1px solid #24485a;border-radius:12px;background:#071b27;color:#dce8ee;cursor:pointer}.pvm-dark{padding:0 9px;font-size:11px}.pvm-dark input{position:absolute;opacity:0;pointer-events:none}.pvm-dark i{width:36px;height:20px;border-radius:999px;background:#385361;padding:2px;display:flex;align-items:center}.pvm-dark i:after{content:"";width:16px;height:16px;border-radius:50%;background:#f1f7fa;transform:translateX(0);transition:.18s}.pvm-dark input:checked+i{background:#18bde8}.pvm-dark input:checked+i:after{transform:translateX(16px)}'+
'#ppVisualMaster .pvm-language{padding:0 9px}.pvm-language select{appearance:none;background:transparent;border:0;outline:0;color:#e8f1f4;font-size:12px;font-weight:850;width:40px}.pvm-language em{font-style:normal;color:#849daa}'+
'#ppVisualMaster .pvm-flag{width:22px;height:16px;display:block;overflow:hidden;border-radius:2px;box-shadow:0 0 0 1px #fff2}.pvm-flag svg{width:22px;height:16px;display:block}'+
'#ppVisualMaster .pvm-hero{position:relative;height:590px;overflow:hidden;display:grid;grid-template-columns:1fr;gap:0;align-items:stretch;padding:18px clamp(30px,4vw,52px) 16px}'+
'#ppVisualMaster .pvm-bg{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center center;filter:contrast(1.16) saturate(1.10) brightness(.99);image-rendering:auto;z-index:0}.pvm-overlay{position:absolute;inset:0;background:linear-gradient(90deg,rgba(4,11,16,.93) 0%,rgba(4,11,16,.68) 24%,rgba(4,11,16,.28) 52%,rgba(4,11,16,.06) 100%),linear-gradient(180deg,rgba(4,11,16,.16),rgba(4,11,16,.24));z-index:1}'+
'#ppVisualMaster .pvm-copy,#ppVisualMaster .pvm-card{position:relative;z-index:2}.pvm-copy{padding-top:56px;max-width:820px}.pvm-kicker{font-size:11px;font-weight:950;letter-spacing:.18em;color:#009FEF;margin-bottom:10px}'+
'#ppVisualMaster h1{margin:0 0 14px;font-size:clamp(48px,5.4vw,72px);line-height:.94;letter-spacing:-.05em;color:#f7f9fa;font-weight:950}.pvm-copy h1 strong{color:#009FEF}.pvm-copy>p{margin:0;color:#bfd0d8;font-size:16px;line-height:1.45}'+
'#ppVisualMaster .pvm-actions{display:flex;gap:12px;margin-top:20px}.pvm-actions button{height:48px;border-radius:12px;padding:0 17px;display:flex;align-items:center;gap:9px;cursor:pointer;font-size:13px;font-weight:900}.pvm-primary{border:1px solid #009FEF;background:linear-gradient(135deg,#19D8FF,#009FEF);color:#fff;box-shadow:0 10px 22px #009FEF28}.pvm-projects{border:1px solid #355564;background:#0a202cdd;color:#edf4f7}.pvm-primary svg,.pvm-projects svg{width:20px;height:20px;fill:none;stroke:#fff;stroke-width:2.2}'+
'#ppVisualMaster .pvm-card{width:450px;min-width:385px;height:260px;align-self:center;border:1px solid #2b5363;border-radius:24px;background:rgba(6,20,29,.60);backdrop-filter:blur(8px);box-shadow:inset 0 1px 0 #fff10,0 24px 60px #0009;overflow:hidden}'+
'#ppVisualMaster .pvm-tagline{position:absolute;left:22px;right:22px;top:22px;bottom:86px;display:flex;align-items:center;justify-content:center;text-align:center;color:#19D8FF;font-family:"Brush Script MT","Segoe Script",cursive;font-size:28px;line-height:1.02;font-style:italic;transform:rotate(-2deg);text-shadow:0 3px 16px #000c;z-index:3}'+
'#ppVisualMaster .pvm-card-strip{position:absolute;left:12px;right:12px;bottom:10px;height:76px;border-top:1px solid #294957;display:grid;grid-template-columns:repeat(7,1fr);align-items:stretch;padding-top:6px}.pvm-card-strip>div{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;text-align:center}.pvm-card-strip>i{width:1px;height:46px;background:#294957;align-self:center}.pvm-card-strip svg{width:25px;height:25px;fill:none;stroke:#009FEF;stroke-width:2.25;stroke-linecap:round;stroke-linejoin:round}.pvm-card-strip>div:nth-child(3) svg{stroke:#19D8FF}.pvm-card-strip>div:nth-child(5) svg{stroke:#10B981}.pvm-card-strip>div:nth-child(7) svg{stroke:#7C4DFF}.pvm-card-strip strong{color:#f2f6f8;font-size:8px;line-height:1.03;white-space:nowrap}.pvm-card-strip small{display:block;color:#9cb0b9;font-size:7px;font-weight:520;margin-top:2px}'+
'#ppVisualMaster .pvm-journey{display:grid;grid-template-columns:minmax(0,1fr) 30px minmax(0,1fr) 28px minmax(0,1fr) 28px minmax(0,1fr);align-items:center;gap:10px;width:min(1140px,calc(100% - 32px));margin:-1px auto 20px;padding-top:12px;position:relative;z-index:4}.pvm-journey button{position:relative;min-width:0;min-height:108px;border:1px solid #2c5260;border-radius:15px;background:linear-gradient(180deg,#0d2330,#091821);color:#fff;padding:13px 16px;display:flex;align-items:center;gap:12px;text-align:left;cursor:pointer;box-shadow:0 10px 24px #0005}.pvm-journey button:hover{transform:translateY(-2px);border-color:#009FEF77}.pvm-journey em{width:28px;height:28px;border:1px solid #355564;border-radius:50%;display:grid;place-items:center;background:#07131b;color:#009FEF;font-size:15px;font-style:normal;font-weight:900}.pvm-journey .n{position:absolute;left:-10px;top:-10px;width:25px;height:25px;padding:0!important;border-radius:50%;display:flex!important;align-items:center!important;justify-content:center!important;text-align:center!important;line-height:1!important;color:#fff;font-size:11px;font-weight:950;border:2px solid #071018;box-shadow:0 0 0 3px #071018;font-family:Inter,Segoe UI,system-ui,sans-serif}.pvm-journey .one{background:#16c5e9}.pvm-journey .two{background:#7C4DFF}.pvm-journey .three{background:#2fd177}.pvm-journey .four{background:#009FEF}.pvm-journey .jicon{width:72px;height:64px;min-width:72px;border:0;border-radius:12px;display:grid;place-items:center;color:#19c8ff;background:transparent;overflow:visible;filter:drop-shadow(0 7px 12px rgba(0,0,0,.38))}.pvm-journey button:nth-of-type(2) .jicon{color:#7C4DFF}.pvm-journey button:nth-of-type(3) .jicon{color:#10B981}.pvm-journey button:nth-of-type(4) .jicon{color:#009FEF}.pvm-journey .jicon svg{width:72px;height:72px;display:block;overflow:visible}.pvm-journey strong{display:block;font-size:14px}.pvm-journey small{display:block;margin-top:4px;color:#9db0ba;font-size:10px;line-height:1.25}'+
'@media(max-width:1180px){#ppVisualMaster .pvm-brand{width:176px;flex-basis:176px}#ppVisualMaster .pvm-hero{grid-template-columns:1fr;gap:0;padding-inline:30px}#ppVisualMaster .pvm-card{width:405px;min-width:365px}.pvm-copy{padding-top:50px}.pvm-copy h1{font-size:54px}}'+
'@media(max-width:900px){#ppVisualMaster .pvm-header{height:auto;min-height:64px;flex-wrap:wrap;padding-block:6px}#ppVisualMaster .pvm-nav{order:3;width:100%;overflow:auto;justify-content:flex-start}#ppVisualMaster .pvm-prefs{margin-left:auto}#ppVisualMaster .pvm-hero{height:auto;min-height:670px;grid-template-columns:1fr;padding:24px 18px 120px}.pvm-copy{padding-top:28px}.pvm-copy h1{font-size:46px}#ppVisualMaster .pvm-card{justify-self:center;width:min(450px,92vw);min-width:0;height:250px}.pvm-journey{grid-template-columns:1fr;gap:12px;width:calc(100% - 20px)}.pvm-journey em{justify-self:center;transform:rotate(90deg)}}'+
'@media(max-width:560px){#ppVisualMaster .pvm-brand{width:150px;flex-basis:150px}#ppVisualMaster .pvm-nav button{font-size:10px;padding-inline:7px;height:42px}#ppVisualMaster .pvm-prefs .pvm-dark b{display:none}#ppVisualMaster .pvm-hero{min-height:650px;padding-bottom:118px}.pvm-copy h1{font-size:39px}.pvm-copy>p{font-size:14px}.pvm-tagline{font-size:22px}.pvm-card{height:230px}.pvm-card-strip{height:66px}.pvm-card-strip svg{width:21px;height:21px}.pvm-card-strip strong{font-size:7px}.pvm-card-strip small{font-size:6px}.pvm-actions{flex-wrap:wrap}}';
style.textContent += '#ppVisualMaster .pvm-tagline{font-family:"Segoe UI",Arial,sans-serif!important;font-size:34px!important;font-weight:800!important;line-height:1.06!important;font-style:italic!important;transform:rotate(-2deg)!important;letter-spacing:.01em!important;text-rendering:geometricPrecision!important;-webkit-font-smoothing:antialiased!important}'+
'#about.result .head>.icon,#about.result .head>.pp-pretty-icon{width:50px!important;height:50px!important;min-width:50px!important;display:grid!important;place-items:center!important;border-radius:12px!important;background:#009FEF12!important;border:2px solid #009FEF!important;color:#fff!important;box-shadow:0 8px 18px rgba(0,0,0,.28),0 0 18px rgba(0,159,239,.12)!important;overflow:visible!important}'+
'#about.result .head>.icon svg,#about.result .head>.pp-pretty-icon svg{width:31px!important;height:31px!important;display:block!important;fill:none!important;stroke:#f7f9fa!important;stroke-width:2.45!important;stroke-linecap:round!important;stroke-linejoin:round!important}'+
'#about.result .head>.icon::before,#about.result .head>.icon::after,#about.result .head>.pp-pretty-icon::before,#about.result .head>.pp-pretty-icon::after{display:none!important;content:none!important}';
style.textContent += '#ppVisualMaster~.shell .panel>.head>.icon,#ppVisualMaster~.shell .panel>.head>.pp-pretty-icon,#ppVisualMaster~.shell .merge-block>.head>.icon,#ppVisualMaster~.shell .merge-block>.head>.pp-pretty-icon{width:60px!important;height:60px!important;min-width:60px!important;flex:0 0 60px!important;border-radius:15px!important;display:grid!important;place-items:center!important;box-sizing:border-box!important;background:linear-gradient(145deg,#132f3d,#0b202c)!important;border:1px solid #3c6676!important;box-shadow:0 8px 20px rgba(0,0,0,.28),inset 0 1px 0 rgba(255,255,255,.05)!important}'+
'#ppVisualMaster~.shell .panel>.head>.icon svg,#ppVisualMaster~.shell .panel>.head>.pp-pretty-icon svg,#ppVisualMaster~.shell .merge-block>.head>.icon svg,#ppVisualMaster~.shell .merge-block>.head>.pp-pretty-icon svg{width:35px!important;height:35px!important;display:block!important;fill:none!important;stroke-width:2.35!important;stroke-linecap:round!important;stroke-linejoin:round!important}'+
'#ppVisualMaster~.shell .pp-profile-card .pp-profile-head{min-height:60px!important;gap:12px!important;align-items:center!important}'+
'#ppVisualMaster~.shell .pp-profile-card .pp-profile-icon{width:60px!important;height:60px!important;min-width:60px!important;flex:0 0 60px!important;border-radius:15px!important;display:grid!important;place-items:center!important;background:linear-gradient(145deg,#132f3d,#0b202c)!important;border:1px solid #3c6676!important;color:#b9c6cd!important;box-shadow:0 8px 20px rgba(0,0,0,.28),inset 0 1px 0 rgba(255,255,255,.05)!important;font-size:0!important}'+
'#ppVisualMaster~.shell .pp-profile-card .pp-profile-icon svg{width:35px!important;height:35px!important;display:block!important;fill:none!important;stroke:currentColor!important;stroke-width:2.35!important;stroke-linecap:round!important;stroke-linejoin:round!important}';
style.textContent += '#ppVisualMaster .pvm-hero-tagline{position:relative;z-index:2;margin:20px 0 0 -85px;color:#19D8FF;font-family:"Segoe UI",Arial,sans-serif;font-size:34px;font-weight:800;line-height:1.06;font-style:italic;letter-spacing:.01em;text-shadow:0 3px 16px #000c;text-align:left;max-width:620px;transform:none!important}';
style.textContent += '#ppVisualMaster .pvm-journey{grid-template-columns:minmax(0,1fr) 34px minmax(0,1fr) 34px minmax(0,1fr) 34px minmax(0,1fr)!important;gap:8px!important;padding-top:18px!important}'+
'#ppVisualMaster .pvm-journey button{min-height:122px!important;padding:12px 14px!important;gap:10px!important}'+
'#ppVisualMaster .pvm-journey .jicon{width:78px!important;height:76px!important;min-width:78px!important;border:0!important;border-radius:10px!important;background:transparent!important;overflow:visible!important;display:grid!important;place-items:center!important;flex:0 0 78px!important;filter:drop-shadow(0 9px 14px rgba(0,0,0,.42))!important}'+
'#ppVisualMaster .pvm-journey .jicon svg{width:78px!important;height:78px!important;max-width:none!important;display:block!important;filter:none!important;overflow:visible!important}'+
'#ppVisualMaster .pvm-journey .jicon + span strong{font-size:14.5px!important;line-height:1.12!important}'+
'#ppVisualMaster .pvm-journey .jicon + span small{font-size:10px!important;line-height:1.22!important}'+
'#ppVisualMaster .pvm-journey em{width:31px!important;height:31px!important;font-size:17px!important;color:#009FEF!important}'+
'@media(max-width:1180px){#ppVisualMaster .pvm-journey .jicon{width:72px!important;min-width:72px!important;height:70px!important}#ppVisualMaster .pvm-journey .jicon svg{width:72px!important;height:72px!important}}'+
'@media(max-width:900px){#ppVisualMaster .pvm-journey{grid-template-columns:1fr!important}.pvm-journey .jicon{width:96px!important;min-width:96px!important;height:90px!important}.pvm-journey .jicon svg{width:96px!important;height:96px!important}}';
document.head.appendChild(style);
const img=top.querySelector('.pvm-brand img');if(img)img.addEventListener('error',()=>{img.style.display='none';top.querySelector('.pvm-brand-fallback').style.display='block'});

const flags={
en:'<svg viewBox="0 0 24 16"><rect width="24" height="16" fill="#123b78"/><path d="M0 0 24 16M24 0 0 16" stroke="#fff" stroke-width="5"/><path d="M0 0 24 16M24 0 0 16" stroke="#c8102e" stroke-width="2"/><path d="M12 0v16M0 8h24" stroke="#fff" stroke-width="6"/><path d="M12 0v16M0 8h24" stroke="#c8102e" stroke-width="3"/></svg>',
pl:'<svg viewBox="0 0 24 16"><path fill="#fff" d="M0 0h24v8H0z"/><path fill="#dc143c" d="M0 8h24v8H0z"/></svg>',
de:'<svg viewBox="0 0 24 16"><path fill="#111" d="M0 0h24v5.33H0z"/><path fill="#d00" d="M0 5.33h24v5.34H0z"/><path fill="#ffce00" d="M0 10.67h24V16H0z"/></svg>',
fr:'<svg viewBox="0 0 24 16"><path fill="#0055a4" d="M0 0h8v16H0z"/><path fill="#fff" d="M8 0h8v16H8z"/><path fill="#ef4135" d="M16 0h8v16h-8z"/></svg>',
es:'<svg viewBox="0 0 24 16"><path fill="#aa151b" d="M0 0h24v4H0z"/><path fill="#f1bf00" d="M0 4h24v8H0z"/><path fill="#aa151b" d="M0 12h24v4H0z"/></svg>',
it:'<svg viewBox="0 0 24 16"><path fill="#009246" d="M0 0h8v16H0z"/><path fill="#fff" d="M8 0h8v16H8z"/><path fill="#ce2b37" d="M16 0h8v16h-8z"/></svg>',
nl:'<svg viewBox="0 0 24 16"><path fill="#ae1c28" d="M0 0h24v5.33H0z"/><path fill="#fff" d="M0 5.33h24v5.34H0z"/><path fill="#21468b" d="M0 10.67h24V16H0z"/></svg>',
pt:'<svg viewBox="0 0 24 16"><path fill="#046a38" d="M0 0h10v16H0z"/><path fill="#da291c" d="M10 0h14v16H10z"/><circle cx="10" cy="8" r="3" fill="#f9e300"/></svg>',
cs:'<svg viewBox="0 0 24 16"><path fill="#fff" d="M0 0h24v8H0z"/><path fill="#d7141a" d="M0 8h24v8H0z"/><path fill="#11457e" d="M0 0l11 8L0 16z"/></svg>',
sv:'<svg viewBox="0 0 24 16"><rect width="24" height="16" fill="#006aa7"/><path stroke="#fecc00" stroke-width="3" d="M8 0v16M0 8h24"/></svg>',
da:'<svg viewBox="0 0 24 16"><rect width="24" height="16" fill="#c8102e"/><path stroke="#fff" stroke-width="3" d="M8 0v16M0 8h24"/></svg>'
};
const lang=top.querySelector('#pvmLanguage');
const flagEl=top.querySelector('.pvm-flag');
const setFlag=()=>{if(!flagEl)return;const code=String(lang?.value||'en').toLowerCase();flagEl.innerHTML=flags[code]||flags.en;flagEl.dataset.language=code;};

let prefs={};try{prefs=JSON.parse(localStorage.getItem('printprofit.preferences.v3')||'{}')||{}}catch(e){}
const dark=top.querySelector('#pvmDarkMode');if(dark)dark.checked=prefs.dark!==false;if(lang)lang.value=prefs.language||'en';setFlag();
dark?.addEventListener('change',()=>{let p={};try{p=JSON.parse(localStorage.getItem('printprofit.preferences.v3')||'{}')||{}}catch(e){}p.dark=dark.checked;localStorage.setItem('printprofit.preferences.v3',JSON.stringify(p));location.reload()});
lang?.addEventListener('input',setFlag);
lang?.addEventListener('change',()=>{setFlag();let p={};try{p=JSON.parse(localStorage.getItem('printprofit.preferences.v3')||'{}')||{}}catch(e){}p.language=String(lang.value||'en');localStorage.setItem('printprofit.preferences.v3',JSON.stringify(p));setTimeout(()=>location.reload(),120)});
window.addEventListener('pageshow',()=>{setFlag();setTimeout(setFlag,50);setTimeout(setFlag,250);});

top.querySelectorAll('[data-a]').forEach(b=>b.addEventListener('click',()=>{
const a=b.getAttribute('data-a');
if(a==='home')window.scrollTo({top:0,behavior:'smooth'});
else if(a==='calculate')goStage('details');
else if(a==='compare')window.top.location.href='./price-finder.html';
else if(a==='guide'&&typeof window.__openPrintProfitGuide==='function')window.__openPrintProfitGuide();
else if(a==='settings'&&typeof window.__openPrintProfitSettings==='function')window.__openPrintProfitSettings();
else if(a==='projects'){b.setAttribute('data-target','projects');b.dispatchEvent(new Event('project-launch',{bubbles:true}))}
}));
top.querySelector('[data-a="projects"]')?.addEventListener('project-launch',()=>{const proxy=document.createElement('button');proxy.type='button';proxy.dataset.target='projects';proxy.hidden=true;document.body.appendChild(proxy);proxy.click();proxy.remove();});
top.querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();goStage(b.getAttribute('data-stage'))}));
return true;
}
function boot(){if(build())return;const t=setInterval(()=>{if(build())clearInterval(t)},50);setTimeout(()=>clearInterval(t),12000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();